# Generated by Django 4.2.6 on 2024-02-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0002_tvshow_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='image1',
            field=models.ImageField(null=True, upload_to='cinema/', verbose_name='Загрузите '),
        ),
    ]
