# Generated by Django 4.2.6 on 2024-02-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0003_tvshow_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='image2',
            field=models.ImageField(null=True, upload_to='cinema/', verbose_name='Загрузите '),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='image3',
            field=models.ImageField(null=True, upload_to='cinema/', verbose_name='Загрузите '),
        ),
    ]
